version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12.14
    commands:
      - pip install -r requirements.txt -t package
  build:
    commands:
      - cd package
      - zip -r ../fastapicalc.zip .
artifacts:
  files:
    - fastapicalc.zip
